"""Add Apple Wallet registrations

Revision ID: 40b95dd9caea
Revises: d6e2114398a8
Create Date: 2026-07-02 12:06:58.131909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b95dd9caea'
down_revision: Union[str, Sequence[str], None] = 'd6e2114398a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apple_wallet_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('device_library_identifier', sa.String(), nullable=False),
    sa.Column('push_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apple_wallet_registrations_id'), 'apple_wallet_registrations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_apple_wallet_registrations_id'), table_name='apple_wallet_registrations')
    op.drop_table('apple_wallet_registrations')
    # ### end Alembic commands ###
