"""Add redemption mode to rewards

Revision ID: 6c20a8a03846
Revises: fa2a3ffc0d41
Create Date: 2026-06-27 18:22:21.013996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c20a8a03846'
down_revision: Union[str, Sequence[str], None] = 'fa2a3ffc0d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('redemption_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'redemption_mode')
    # ### end Alembic commands ###
