"""Add unique credential provider constraint

Revision ID: 863824adce01
Revises: 6a98a2220801
Create Date: 2026-07-02 16:32:31.106519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863824adce01'
down_revision: Union[str, Sequence[str], None] = '6a98a2220801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_credential_card_provider', 'credentials', ['loyalty_card_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_credential_card_provider', 'credentials', type_='unique')
    # ### end Alembic commands ###
