"""Add flexible loyalty program types

Revision ID: 871d8ee98af0
Revises: 9170318de3bf
Create Date: 2026-06-27 12:37:19.843967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871d8ee98af0'
down_revision: Union[str, Sequence[str], None] = '9170318de3bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loyalty_programs', sa.Column('program_type', sa.String(), nullable=True))
    op.add_column('loyalty_programs', sa.Column('earn_unit', sa.String(), nullable=True))
    op.add_column('loyalty_programs', sa.Column('earn_rate', sa.Float(), nullable=True))
    op.add_column('loyalty_programs', sa.Column('target_count', sa.Integer(), nullable=True))
    op.add_column('loyalty_programs', sa.Column('target_reward_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loyalty_programs', 'target_reward_description')
    op.drop_column('loyalty_programs', 'target_count')
    op.drop_column('loyalty_programs', 'earn_rate')
    op.drop_column('loyalty_programs', 'earn_unit')
    op.drop_column('loyalty_programs', 'program_type')
    # ### end Alembic commands ###
