"""Update rewards table

Revision ID: 9170318de3bf
Revises: b831b32dae6f
Create Date: 2026-06-27 12:00:15.708546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9170318de3bf'
down_revision: Union[str, Sequence[str], None] = 'b831b32dae6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('reward_type', sa.String(), nullable=True))
    op.add_column('rewards', sa.Column('reward_value', sa.String(), nullable=True))
    op.add_column('rewards', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'is_active')
    op.drop_column('rewards', 'reward_value')
    op.drop_column('rewards', 'reward_type')
    # ### end Alembic commands ###
