"""Add loyalty program table

Revision ID: b831b32dae6f
Revises: b7f3e092864f
Create Date: 2026-06-27 11:28:13.935936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b831b32dae6f'
down_revision: Union[str, Sequence[str], None] = 'b7f3e092864f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loyalty_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('points_per_currency_unit', sa.Float(), nullable=True),
    sa.Column('currency_unit', sa.String(), nullable=True),
    sa.Column('welcome_bonus_points', sa.Integer(), nullable=True),
    sa.Column('birthday_bonus_points', sa.Integer(), nullable=True),
    sa.Column('referral_bonus_points', sa.Integer(), nullable=True),
    sa.Column('points_expire', sa.Boolean(), nullable=True),
    sa.Column('expiration_months', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_index(op.f('ix_loyalty_programs_id'), 'loyalty_programs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loyalty_programs_id'), table_name='loyalty_programs')
    op.drop_table('loyalty_programs')
    # ### end Alembic commands ###
