"""Add last updated to wallet registrations

Revision ID: c0194b4fc739
Revises: 40b95dd9caea
Create Date: 2026-07-02 13:21:50.196372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0194b4fc739'
down_revision: Union[str, Sequence[str], None] = '40b95dd9caea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apple_wallet_registrations', sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apple_wallet_registrations', 'last_updated_at')
    # ### end Alembic commands ###
