"""Update loyalty cards

Revision ID: ce146aa43e56
Revises: 53a1318be60f
Create Date: 2026-06-28 17:55:32.491546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce146aa43e56'
down_revision: Union[str, Sequence[str], None] = '53a1318be60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loyalty_cards', sa.Column('public_id', sa.String(), nullable=False))
    op.add_column('loyalty_cards', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_loyalty_cards_public_id'), 'loyalty_cards', ['public_id'], unique=True)
    op.create_unique_constraint(None, 'loyalty_cards', ['customer_id'])
    op.drop_column('loyalty_cards', 'points_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loyalty_cards', sa.Column('points_balance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'loyalty_cards', type_='unique')
    op.drop_index(op.f('ix_loyalty_cards_public_id'), table_name='loyalty_cards')
    op.drop_column('loyalty_cards', 'status')
    op.drop_column('loyalty_cards', 'public_id')
    # ### end Alembic commands ###
