"""Update customer model

Revision ID: cffdf0a7011b
Revises: 6c20a8a03846
Create Date: 2026-06-27 19:02:04.787433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cffdf0a7011b'
down_revision: Union[str, Sequence[str], None] = '6c20a8a03846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('location_id', sa.Integer(), nullable=False))
    op.add_column('customers', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('customers', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('customers', sa.Column('current_progress', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('total_rewards_redeemed', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'customers', 'locations', ['location_id'], ['id'])
    op.drop_column('customers', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'is_active')
    op.drop_column('customers', 'total_rewards_redeemed')
    op.drop_column('customers', 'current_progress')
    op.drop_column('customers', 'date_of_birth')
    op.drop_column('customers', 'last_name')
    op.drop_column('customers', 'first_name')
    op.drop_column('customers', 'location_id')
    # ### end Alembic commands ###
