"""Add storage path to credentials

Revision ID: d6e2114398a8
Revises: 0234050789cf
Create Date: 2026-06-30 23:35:36.836453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e2114398a8'
down_revision: Union[str, Sequence[str], None] = '0234050789cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('storage_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credentials', 'storage_path')
    # ### end Alembic commands ###
