"""Create wallet pass domain

Revision ID: f5f0ad754ba9
Revises: 1b5fd1a1a4de
Create Date: 2026-06-29 14:11:34.379797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f0ad754ba9'
down_revision: Union[str, Sequence[str], None] = '1b5fd1a1a4de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_passes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loyalty_card_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('authentication_token', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['loyalty_card_id'], ['loyalty_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_passes_id'), 'wallet_passes', ['id'], unique=False)
    op.drop_column('loyalty_cards', 'apple_pass_url')
    op.drop_column('loyalty_cards', 'google_pass_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loyalty_cards', sa.Column('google_pass_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('loyalty_cards', sa.Column('apple_pass_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_wallet_passes_id'), table_name='wallet_passes')
    op.drop_table('wallet_passes')
    # ### end Alembic commands ###
