"""Add redemption behavior to rewards

Revision ID: fa2a3ffc0d41
Revises: 615202f5be93
Create Date: 2026-06-27 16:32:07.301210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2a3ffc0d41'
down_revision: Union[str, Sequence[str], None] = '615202f5be93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('redemption_behavior', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'redemption_behavior')
    # ### end Alembic commands ###
